# -*- coding: utf-8 -*-
"""BTL Hệ thống thông tin nâng cao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/167UJwmAUNpQ2OhxcaCKQK8KCG5jZQB3C
"""

!pip install torch
!pip install torch-geometric
!pip install numpy
!pip install matplotlib



import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import GCNConv
import numpy as np
import matplotlib.pyplot as plt

# ================================
# Simulation parameters
# ================================

NUM_USERS = 10
AREA_SIZE = 100
NOISE = 1e-9
MAX_POWER = 1.0

# ================================
# Generate wireless network
# ================================

def generate_network(num_users):

    positions = np.random.rand(num_users,2) * AREA_SIZE

    channel_gain = np.zeros((num_users,num_users))

    for i in range(num_users):
        for j in range(num_users):

            dist = np.linalg.norm(positions[i] - positions[j]) + 1e-3

            pathloss = 1 / (dist**2)

            fading = np.random.rayleigh()

            channel_gain[i,j] = pathloss * fading

    return positions, channel_gain

# ================================
# Graph construction
# ================================

def build_graph(channel_gain):

    edge_index = []
    edge_weight = []

    N = channel_gain.shape[0]

    for i in range(N):
        for j in range(N):
            if i != j:

                edge_index.append([i,j])
                edge_weight.append(channel_gain[i,j])

    edge_index = torch.tensor(edge_index).t().contiguous()
    edge_weight = torch.tensor(edge_weight, dtype=torch.float)

    return edge_index, edge_weight

# ================================
# Node features
# ================================

def build_node_features(channel_gain):

    N = channel_gain.shape[0]

    features = []

    for i in range(N):

        gain = channel_gain[i,i]

        interference = np.sum(channel_gain[:,i]) - gain

        demand = np.random.rand()

        features.append([gain, interference, demand])

    return torch.tensor(features, dtype=torch.float)

# ================================
# GNN Model
# ================================

class GNN(nn.Module):

    def __init__(self):

        super(GNN,self).__init__()

        self.conv1 = GCNConv(3,16)
        self.conv2 = GCNConv(16,16)

        self.fc = nn.Linear(16,1)

    def forward(self, x, edge_index):

        x = self.conv1(x, edge_index)
        x = F.relu(x)

        x = self.conv2(x, edge_index)
        x = F.relu(x)

        power = torch.sigmoid(self.fc(x))

        return power * MAX_POWER

# ================================
# Throughput calculation
# ================================

def compute_sum_rate(power, channel_gain):

    N = len(power)

    sum_rate = 0

    for i in range(N):

        signal = power[i] * channel_gain[i,i]

        interference = 0

        for j in range(N):

            if j != i:
                interference += power[j] * channel_gain[j,i]

        sinr = signal / (interference + NOISE)

        rate = np.log2(1 + sinr)

        sum_rate += rate

    return sum_rate

# ================================
# Training loop
# ================================

model = GNN()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

epochs = 200

reward_history = []

for epoch in range(epochs):

    positions, channel_gain = generate_network(NUM_USERS)

    edge_index, edge_weight = build_graph(channel_gain)

    x = build_node_features(channel_gain)

    power = model(x, edge_index)

    power_np = power.detach().numpy().flatten()

    sum_rate = compute_sum_rate(power_np, channel_gain)

    loss = -torch.tensor(sum_rate, requires_grad=True)

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    reward_history.append(sum_rate)

    if epoch % 20 == 0:

        print("Epoch:",epoch," SumRate:",sum_rate)

# ================================
# Plot result
# ================================

plt.plot(reward_history)
plt.xlabel("Epoch")
plt.ylabel("Network Throughput")
plt.title("Edge GNN Wireless Resource Allocation")
plt.show()

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GCNConv
import numpy as np
import matplotlib.pyplot as plt

# =============================
# Parameters
# =============================

NUM_USERS = 10
AREA_SIZE = 10
NOISE = 1e-9
MAX_POWER = 1.0
EPOCHS = 500

# =============================
# Wireless Network Generator
# =============================

def generate_network(num_users):

    positions = np.random.rand(num_users,2) * AREA_SIZE

    channel_gain = np.zeros((num_users,num_users))

    for i in range(num_users):
        for j in range(num_users):

            dist = np.linalg.norm(positions[i] - positions[j]) + 1e-3
            pathloss = 1/(dist)
            fading = np.random.rayleigh()

            channel_gain[i,j] = pathloss * fading

    return torch.tensor(channel_gain,dtype=torch.float)


# =============================
# Graph Construction
# =============================

def build_graph(channel_gain):

    N = channel_gain.shape[0]

    edge_index = []

    for i in range(N):
        for j in range(N):
            if i != j:
                edge_index.append([i,j])

    edge_index = torch.tensor(edge_index).t().contiguous()

    return edge_index


# =============================
# Node Features
# =============================

def build_node_features(channel_gain):

    N = channel_gain.shape[0]

    features = []

    for i in range(N):

        gain = channel_gain[i,i]

        interference = torch.sum(channel_gain[:,i]) - gain

        demand = torch.rand(1)

        features.append(torch.tensor([gain,interference,demand]))

    return torch.stack(features)


# =============================
# GNN Model
# =============================

class GNN(nn.Module):

    def __init__(self):

        super(GNN,self).__init__()

        self.conv1 = GCNConv(3,32)
        self.conv2 = GCNConv(32,32)
        self.conv3 = GCNConv(32,16)

        self.fc = nn.Linear(16,1)

    def forward(self,x,edge_index):

        x = self.conv1(x,edge_index)
        x = F.relu(x)

        x = self.conv2(x,edge_index)
        x = F.relu(x)

        x = self.conv3(x,edge_index)
        x = F.relu(x)

        power = 0.5 + 0.5*torch.sigmoid(self.fc(x))

        return power.squeeze() * MAX_POWER


# =============================
# Throughput Calculation
# =============================

def compute_sum_rate(power,channel_gain):

    N = len(power)

    sum_rate = 0

    for i in range(N):

        signal = power[i] * channel_gain[i,i]

        interference = torch.sum(power * channel_gain[:,i]) - signal

        sinr = signal / (interference + NOISE)

        rate = torch.log2(1 + sinr)

        sum_rate += rate

    return sum_rate


# =============================
# Training
# =============================

model = GNN()

optimizer = torch.optim.Adam(model.parameters(),lr=0.003)

reward_history = []

for epoch in range(EPOCHS):

    channel_gain = generate_network(NUM_USERS)

    edge_index = build_graph(channel_gain)

    x = build_node_features(channel_gain)

    power = model(x,edge_index)

    sum_rate = compute_sum_rate(power,channel_gain)

    loss = -sum_rate

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    reward_history.append(sum_rate.item())

    if epoch % 50 == 0:

        print("Epoch:",epoch," Throughput:",sum_rate.item())


# =============================
# Plot result
# =============================

plt.figure(figsize=(8,4))
plt.plot(reward_history)
plt.xlabel("Epoch")
plt.ylabel("Network Throughput")
plt.title("Edge AI GNN Wireless Resource Allocation Learning")
plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

# ----------------------------
# Simulation parameters
# ----------------------------

num_users = 10
epochs = 500
power_budget = 10

# Random wireless channel gains
channel_gains = torch.rand(num_users)

# ----------------------------
# Graph Adjacency (fully connected)
# ----------------------------

adj = torch.ones(num_users, num_users)
adj.fill_diagonal_(0)

# ----------------------------
# Simple GNN Model
# ----------------------------

class GNN(nn.Module):

    def __init__(self, in_features, hidden):
        super(GNN, self).__init__()

        self.fc1 = nn.Linear(in_features, hidden)
        self.fc2 = nn.Linear(hidden, 1)

    def forward(self, x, adj):

        agg = torch.matmul(adj, x)
        h = torch.relu(self.fc1(agg))
        out = self.fc2(h)

        return torch.softmax(out.squeeze(), dim=0)

model = GNN(1, 16)

optimizer = optim.Adam(model.parameters(), lr=0.01)

# ----------------------------
# Throughput storage
# ----------------------------

throughputs = []

# ----------------------------
# Training loop
# ----------------------------

for epoch in range(epochs):

    x = channel_gains.view(-1,1)

    alloc = model(x, adj)

    power = alloc * power_budget

    sinr = channel_gains * power

    throughput = torch.sum(torch.log2(1 + sinr))

    loss = -throughput

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    throughputs.append(throughput.item())

    if epoch % 50 == 0:
        print(f"Epoch {epoch}  Throughput: {throughput.item():.3f}")

# ----------------------------
# Plotting (Research Style)
# ----------------------------

throughputs = np.array(throughputs)

# Moving average
window = 20
smooth = np.convolve(throughputs, np.ones(window)/window, mode='valid')

plt.figure(figsize=(10,5))

plt.plot(throughputs, alpha=0.4, label="Raw Throughput")
plt.plot(range(window-1,len(throughputs)), smooth, linewidth=2, label="Smoothed Throughput")

plt.xlabel("Epoch")
plt.ylabel("Network Throughput")
plt.title("Edge AI GNN Wireless Resource Allocation Learning")
plt.legend()
plt.grid(True)

plt.show()

"""version cải tiến

"""

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

# ----------------------------
# Parameters
# ----------------------------

num_users = 10
epochs = 500
power_budget = 10
noise = 1e-2

# ----------------------------
# Generate user positions
# ----------------------------

positions = torch.rand(num_users, 2)  # (x,y)

# Distance-based adjacency
dist_matrix = torch.cdist(positions, positions)

adj = torch.exp(-dist_matrix)  # closer → stronger interference
adj.fill_diagonal_(0)

# ----------------------------
# GNN Model (improved)
# ----------------------------

class GNN(nn.Module):
    def __init__(self):
        super(GNN, self).__init__()

        self.fc1 = nn.Linear(1, 32)
        self.fc2 = nn.Linear(32, 32)
        self.fc3 = nn.Linear(32, 1)

    def forward(self, x, adj):

        # Message passing
        agg = torch.matmul(adj, x)

        h = torch.relu(self.fc1(agg))
        h = torch.relu(self.fc2(h))
        out = self.fc3(h)

        # Softmax → allocation ratio
        alloc = torch.softmax(out.squeeze(), dim=0)

        return alloc

model = GNN()
optimizer = optim.Adam(model.parameters(), lr=0.005)

# ----------------------------
# Training
# ----------------------------

throughputs = []

for epoch in range(epochs):

    # 🔥 Random channel mỗi epoch
    channel_gains = torch.rand(num_users)

    x = channel_gains.view(-1,1)

    # Forward
    alloc = model(x, adj)

    # Power allocation
    power = alloc * power_budget

    # 🔥 SINR chuẩn (có interference)
    interference = torch.matmul(adj, (power * channel_gains))
    signal = power * channel_gains

    sinr = signal / (interference + noise)

    # Throughput
    throughput = torch.sum(torch.log2(1 + sinr))

    # Loss
    loss = -throughput

    # Backprop
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    throughputs.append(throughput.item())

    if epoch % 50 == 0:
        print(f"Epoch {epoch} | Throughput: {throughput.item():.3f}")

# ----------------------------
# Plot (IEEE style)
# ----------------------------

throughputs = np.array(throughputs)

# Moving average
window = 20
smooth = np.convolve(throughputs, np.ones(window)/window, mode='valid')

plt.figure(figsize=(10,5))

plt.plot(throughputs, alpha=0.4, label="Raw Throughput")
plt.plot(range(window-1, len(throughputs)), smooth, linewidth=2, label="Smoothed Throughput")

plt.xlabel("Epoch")
plt.ylabel("Network Throughput")
plt.title("Improved Edge AI GNN Wireless Resource Allocation")
plt.legend()
plt.grid(True)

plt.show()